const items = [
    {
        id: '001',
        image_name: '1.jpg',
        company_name: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        prev_price: 1045,
        current_price: 606,
        discount : 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image_name: '2.jpg',
        company_name: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        prev_price: 2599,
        current_price: 1507,
        discount: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image_name: '3.jpg',
        company_name: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        prev_price: 1599,
        current_price: 495,
        discount : 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image_name: '4.jpg',
        company_name: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        prev_price: 999,
        current_price: 999,
        discount : 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image_name: '5.jpg',
        company_name: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        prev_price: 1399,
        current_price: 489,
        discount : 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image_name: '6.jpg',
        company_name: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        prev_price: 14995,
        current_price: 14995,
        discount : 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image_name: '7.jpg',
        company_name: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        prev_price: 1599,
        current_price: 639,
        discount : 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image_name: '8.jpg',
        company_name: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        prev_price: 285,
        current_price: 142,
        discount : 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];